kube-prometheus-stack:
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: grafana-password
    service:
      type: NodePort
      nodePort: 32000

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false

  serviceMonitors:
    - name: drupal
      selector:
        matchLabels:
          app.kubernetes.io/name: drupal
      endpoints:
        - port: http
          interval: 15s

  alertmanager:
    enabled: true

  prometheusOperator:
    createCustomResource: true
 
  prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
