controller:
  replicaCount: 1
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  admissionWebhooks:
    enabled: true
  metrics:
    enabled: true

defaultBackend:
  enabled: true
